### ISSUE TITLE
Weather dew point italian

### ISSUE THREAD

**Issue by mapi68** [Ch3dd4rGoblin/skin.TetradUI#42]
Hello, can you enlarge Dew Point from Weather window?
In italian is "Punto di rugiada"

![2023-03-13_005919](https://user-images.githubusercontent.com/41143572/224582311-95cff147-843a-4fdd-bc88-67773df80efb.png)

**Comment by gade01** [comment]
@mapi68 This should be an easy fix.
Is this still needed?

**Comment by mapi68** [comment]
Yes

**Comment by gade01** [comment]
Thanks, I'll look into it ;)
